#!/bin/bash
sleep 10
if [[ `sudo systemctl status docker|grep -o "inactive"` = "inactive" ]]; then
    sudo systemctl start docker
fi 

#if [[ `sudo systemctl status rabbitmq-server | grep -o "inactive"` = "inactive" ]]; then
#    sudo systemctl start rabbitmq-server 
#fi

notify-send "Delay Start Services" "Docker `sudo systemctl status docker | grep -oP "^ .*Active: \w*"|grep -oP ": \w*"`"
