#!/bin/bash
password=`cat /home/sajith/scratch/myconfigs/mail/password`
if [[ -z "$password" ]]; then 
    echo "Password empty"
else
    url="/usr/bin/curl -su  sajith.silva@pagero.com:$password https://mail.google.com/mail/feed/atom"    
    response=`$url`

    if [[ `echo "$response" | grep "<TITLE>Unauthorized</TITLE>"|wc -l` -eq "1" ]]; then
        /usr/bin/notify-send "gmail authentication failed"
        echo "auth failed"
    elif [[ `echo "$response" | grep "<fullcount>0</fullcount>" | wc -l` -eq "1" ]]; then
        echo "no mail"
    else
        echo "has mail"
        /usr/bin/notify-send "මේල් ආවා"
    fi
fi
